# Generated by Django 5.0.3 on 2024-04-16 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeshoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_number', models.IntegerField(blank=True, default=0, null=True)),
                ('amount_in_ugx', models.IntegerField(blank=True, default=0, null=True)),
                ('currency', models.CharField(blank=True, default='Shs.', max_length=5, null=True)),
                ('c_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KeshoApp.categorystay')),
            ],
        ),
        migrations.AddField(
            model_name='babe',
            name='c_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KeshoApp.payment'),
        ),
    ]
