# Generated by Django 5.0.3 on 2024-04-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KeshoApp', '0002_payment_babe_c_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount_in_ugx',
            new_name='amount',
        ),
    ]
